-- Schema Oracle pour le projet Atelier_Connexion
-- A executer avec un compte DBA (SYSTEM, SYSDBA, etc.)

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER awss IDENTIFIED BY "123"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

ALTER USER awss IDENTIFIED BY "123" ACCOUNT UNLOCK;
ALTER USER awss DEFAULT TABLESPACE USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO awss;
ALTER USER awss QUOTA UNLIMITED ON USERS;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AWSS.MAINTENANCE_PREDICTIVE CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AWSS.EXTRACTION CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AWSS.RECEPTION CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AWSS.CITERNE CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AWSS.MACHINE CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AWSS.CLIENT CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE AWSS.SEQ_CLIENT';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE AWSS.SEQ_CITERNE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE AWSS.SEQ_MACHINE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE AWSS.SEQ_MAINTENANCE_PREDICTIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER AWSS.TRG_CLIENT_BI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER AWSS.TRG_CITERNE_BI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER AWSS.TRG_MACHINE_BI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER AWSS.TRG_MAINTENANCE_PREDICTIVE_BI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

CREATE TABLE AWSS.CLIENT (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(120) NOT NULL,
  EMAIL VARCHAR2(180),
  PHONE VARCHAR2(40),
  ADDRESS VARCHAR2(240),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(30)
);

CREATE TABLE AWSS.MACHINE (
  ID NUMBER PRIMARY KEY,
  NOM VARCHAR2(120) NOT NULL,
  QUALITE VARCHAR2(80)
);

CREATE TABLE AWSS.CITERNE (
  ID NUMBER PRIMARY KEY,
  CODE VARCHAR2(40) NOT NULL UNIQUE,
  CAPACITY_L NUMBER(12,2) NOT NULL,
  CURRENT_VOLUME_L NUMBER(12,2) DEFAULT 0 NOT NULL,
  QUALITY_INDEX NUMBER(6,2),
  TEMPERATURE_C NUMBER(5,2),
  LAST_FILLING_AT DATE,
  STATUS VARCHAR2(30),
  CONSTRAINT CK_CITERNE_CAP_POSITIVE CHECK (CAPACITY_L > 0),
  CONSTRAINT CK_CITERNE_VOL_VALID CHECK (CURRENT_VOLUME_L >= 0 AND CURRENT_VOLUME_L <= CAPACITY_L)
);

CREATE TABLE AWSS.RECEPTION (
  ID NUMBER PRIMARY KEY,
  LOT_NUMBER VARCHAR2(80) NOT NULL UNIQUE,
  RECEIVED_AT DATE DEFAULT SYSDATE NOT NULL,
  QUANTITY_KG NUMBER(12,2) NOT NULL,
  QUALITY_GRADE VARCHAR2(40),
  CLIENT_ID NUMBER,
  STATUS VARCHAR2(30),
  CONSTRAINT FK_RECEPTION_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES AWSS.CLIENT(ID)
);

CREATE TABLE AWSS.EXTRACTION (
  ID NUMBER PRIMARY KEY,
  LOT_ID NUMBER,
  MACHINE_ID NUMBER,
  TARGET_CITERNE_ID NUMBER,
  EXTRACTED_AT DATE DEFAULT SYSDATE,
  INPUT_QUANTITY_KG NUMBER(12,2),
  OUTPUT_OIL_L NUMBER(12,2),
  YIELD_PERCENTAGE NUMBER(6,2),
  QUALITY_RESULT VARCHAR2(80),
  STATUS VARCHAR2(30),
  CONSTRAINT FK_EXTRACTION_RECEPTION FOREIGN KEY (LOT_ID) REFERENCES AWSS.RECEPTION(ID),
  CONSTRAINT FK_EXTRACTION_CITERNE FOREIGN KEY (TARGET_CITERNE_ID) REFERENCES AWSS.CITERNE(ID),
  CONSTRAINT FK_EXTRACTION_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES AWSS.MACHINE(ID)
);

CREATE TABLE AWSS.MAINTENANCE_PREDICTIVE (
  ID NUMBER PRIMARY KEY,
  MACHINE_ID NUMBER,
  CITERNE_ID NUMBER,
  PREDICTED_AT DATE DEFAULT SYSDATE,
  PREDICTED_ISSUE VARCHAR2(255),
  RISK_LEVEL VARCHAR2(30),
  RECOMMENDED_ACTION VARCHAR2(255),
  STATUS VARCHAR2(30),
  CONSTRAINT FK_MAINT_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES AWSS.MACHINE(ID),
  CONSTRAINT FK_MAINT_CITERNE FOREIGN KEY (CITERNE_ID) REFERENCES AWSS.CITERNE(ID)
);

CREATE SEQUENCE AWSS.SEQ_CLIENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AWSS.SEQ_CITERNE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AWSS.SEQ_MACHINE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AWSS.SEQ_MAINTENANCE_PREDICTIVE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AWSS.SEQ_RECEPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AWSS.SEQ_EXTRACTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER AWSS.TRG_CLIENT_BI
BEFORE INSERT ON AWSS.CLIENT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT AWSS.SEQ_CLIENT.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER AWSS.TRG_CITERNE_BI
BEFORE INSERT ON AWSS.CITERNE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT AWSS.SEQ_CITERNE.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER AWSS.TRG_MACHINE_BI
BEFORE INSERT ON AWSS.MACHINE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT AWSS.SEQ_MACHINE.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER AWSS.TRG_MAINTENANCE_PREDICTIVE_BI
BEFORE INSERT ON AWSS.MAINTENANCE_PREDICTIVE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT AWSS.SEQ_MAINTENANCE_PREDICTIVE.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER AWSS.TRG_RECEPTION_BI
BEFORE INSERT ON AWSS.RECEPTION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT AWSS.SEQ_RECEPTION.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER AWSS.TRG_EXTRACTION_BI
BEFORE INSERT ON AWSS.EXTRACTION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT AWSS.SEQ_EXTRACTION.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

INSERT INTO AWSS.CLIENT (NAME, EMAIL, PHONE, ADDRESS, STATUS)
VALUES ('Client test', 'client@test.local', '0600000000', 'Adresse test', 'ACTIF');

INSERT INTO AWSS.MACHINE (NOM, QUALITE)
VALUES ('Machine 1', 'OK');

INSERT INTO AWSS.CITERNE (CODE, CAPACITY_L, CURRENT_VOLUME_L, QUALITY_INDEX, TEMPERATURE_C, LAST_FILLING_AT, STATUS)
VALUES ('CT-001', 1000, 200, 85, 25, SYSDATE, 'ACTIF');

INSERT INTO AWSS.RECEPTION (LOT_NUMBER, QUANTITY_KG, QUALITY_GRADE, CLIENT_ID, STATUS)
VALUES ('LOT-001', 500, 'A', 1, 'RECU');

INSERT INTO AWSS.EXTRACTION (LOT_ID, MACHINE_ID, TARGET_CITERNE_ID, EXTRACTED_AT, INPUT_QUANTITY_KG, OUTPUT_OIL_L, YIELD_PERCENTAGE, QUALITY_RESULT, STATUS)
VALUES (1, 1, 1, SYSDATE, 500, 90, 18, 'BONNE', 'PLANIFIE');

INSERT INTO AWSS.MAINTENANCE_PREDICTIVE (MACHINE_ID, CITERNE_ID, PREDICTED_AT, PREDICTED_ISSUE, RISK_LEVEL, RECOMMENDED_ACTION, STATUS)
VALUES (1, 1, SYSDATE, 'Usure normale detectee', 'FAIBLE', 'Surveillance standard', 'ACTIF');

COMMIT;

EXIT;