######################################################################
# Automatically generated by qmake (3.1) Thu Apr 23 08:55:59 2026
######################################################################

TEMPLATE = app
TARGET = test_qoci
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += citerne.h \
           client.h \
           connection.h \
           extraction.h \
           mainwindow.h \
           reception.h \
           ui_mainwindow.h \
           Atelier_Connexion/connection.h \
           Atelier_Connexion/mainwindow.h \
           /ui_mainwindow.h
FORMS += Atelier_Connexion/mainwindow.ui
SOURCES += citerne.cpp \
           client.cpp \
           connection.cpp \
           extraction.cpp \
           main.cpp \
           mainwindow.cpp \
           reception.cpp \
           test_qoci.cpp \
           /test_qoci.cpp \
           Atelier_Connexion/connection.cpp \
           Atelier_Connexion/main.cpp \
           Atelier_Connexion/mainwindow.cpp
