/* =========================================================
   SCHEMA ORACLE SANS BLENDING - VERSION FINALE
   ========================================================= */

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE_PREDICTIVE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXTRACTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECEPTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CITERNE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MACHINE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MAINTENANCE_PRED_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_EXTRACTION_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_RECEPTION_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CITERNE_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MACHINE_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CLIENT_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAINTENANCE_PREDICTIVE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EXTRACTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECEPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CITERNE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MACHINE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE CLIENT (
    ID          NUMBER PRIMARY KEY,
    NAME        VARCHAR2(120) NOT NULL,
    EMAIL       VARCHAR2(180),
    PHONE       VARCHAR2(40),
    ADDRESS     VARCHAR2(240),
    CREATED_AT  DATE DEFAULT SYSDATE NOT NULL,
    STATUS      VARCHAR2(30)
);

CREATE TABLE MACHINE (
    ID       NUMBER PRIMARY KEY,
    NOM      VARCHAR2(120) NOT NULL,
    QUALITE  VARCHAR2(60)
);

CREATE TABLE CITERNE (
    ID                NUMBER PRIMARY KEY,
    CODE              VARCHAR2(40) NOT NULL UNIQUE,
    CAPACITY_L        NUMBER(12,2) NOT NULL,
    CURRENT_VOLUME_L  NUMBER(12,2) DEFAULT 0 NOT NULL,
    QUALITY_INDEX     NUMBER(6,2),
    TEMPERATURE_C     NUMBER(5,2),
    LAST_FILLING_AT   DATE,
    STATUS            VARCHAR2(30),
    CONSTRAINT CK_CITERNE_CAP_POSITIVE CHECK (CAPACITY_L > 0),
    CONSTRAINT CK_CITERNE_VOL_VALID CHECK (CURRENT_VOLUME_L >= 0 AND CURRENT_VOLUME_L <= CAPACITY_L)
);

CREATE TABLE RECEPTION (
    ID             NUMBER PRIMARY KEY,
    LOT_NUMBER     VARCHAR2(80) NOT NULL UNIQUE,
    RECEIVED_AT    DATE NOT NULL,
    QUANTITY_KG    NUMBER(12,2) NOT NULL,
    QUALITY_GRADE  VARCHAR2(60),
    CLIENT_ID      NUMBER NOT NULL,
    STATUS         VARCHAR2(30),
    CONSTRAINT FK_RECEPTION_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT(ID),
    CONSTRAINT CK_RECEPTION_QTY_POSITIVE CHECK (QUANTITY_KG > 0)
);

CREATE TABLE EXTRACTION (
    ID                 NUMBER PRIMARY KEY,
    LOT_ID             NUMBER NOT NULL UNIQUE,
    MACHINE_ID         NUMBER NOT NULL,
    TARGET_CITERNE_ID  NUMBER NOT NULL,
    EXTRACTED_AT       DATE NOT NULL,
    INPUT_QUANTITY_KG  NUMBER(12,2) NOT NULL,
    OUTPUT_OIL_L       NUMBER(12,2),
    YIELD_PERCENTAGE   NUMBER(6,2),
    QUALITY_RESULT     VARCHAR2(60),
    STATUS             VARCHAR2(30)
);

ALTER TABLE EXTRACTION ADD CONSTRAINT FK_EXTRACTION_LOT
    FOREIGN KEY (LOT_ID) REFERENCES RECEPTION(ID);
ALTER TABLE EXTRACTION ADD CONSTRAINT FK_EXTRACTION_MACHINE
    FOREIGN KEY (MACHINE_ID) REFERENCES MACHINE(ID);
ALTER TABLE EXTRACTION ADD CONSTRAINT FK_EXTRACTION_CITERNE
    FOREIGN KEY (TARGET_CITERNE_ID) REFERENCES CITERNE(ID);
ALTER TABLE EXTRACTION ADD CONSTRAINT CK_EXTRACTION_IN_POSITIVE
    CHECK (INPUT_QUANTITY_KG > 0);
ALTER TABLE EXTRACTION ADD CONSTRAINT CK_EXTRACTION_OUT_NONNEG
    CHECK (OUTPUT_OIL_L IS NULL OR OUTPUT_OIL_L >= 0);
ALTER TABLE EXTRACTION ADD CONSTRAINT CK_EXTRACTION_YIELD
    CHECK (YIELD_PERCENTAGE IS NULL OR (YIELD_PERCENTAGE >= 0 AND YIELD_PERCENTAGE <= 100));

CREATE TABLE MAINTENANCE_PREDICTIVE (
    ID                  NUMBER PRIMARY KEY,
    MACHINE_ID          NUMBER NOT NULL,
    CITERNE_ID          NUMBER,
    PREDICTED_AT        DATE NOT NULL,
    PREDICTED_ISSUE     VARCHAR2(200) NOT NULL,
    RISK_LEVEL          VARCHAR2(20),
    RECOMMENDED_ACTION  VARCHAR2(300),
    STATUS              VARCHAR2(30)
);

ALTER TABLE MAINTENANCE_PREDICTIVE ADD CONSTRAINT FK_MP_MACHINE
    FOREIGN KEY (MACHINE_ID) REFERENCES MACHINE(ID);
ALTER TABLE MAINTENANCE_PREDICTIVE ADD CONSTRAINT FK_MP_CITERNE
    FOREIGN KEY (CITERNE_ID) REFERENCES CITERNE(ID);

CREATE SEQUENCE SEQ_CLIENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MACHINE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CITERNE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RECEPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXTRACTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAINTENANCE_PREDICTIVE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CLIENT_BI
BEFORE INSERT ON CLIENT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_CLIENT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MACHINE_BI
BEFORE INSERT ON MACHINE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_MACHINE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CITERNE_BI
BEFORE INSERT ON CITERNE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_CITERNE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RECEPTION_BI
BEFORE INSERT ON RECEPTION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_RECEPTION.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXTRACTION_BI
BEFORE INSERT ON EXTRACTION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_EXTRACTION.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MAINTENANCE_PRED_BI
BEFORE INSERT ON MAINTENANCE_PREDICTIVE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_MAINTENANCE_PREDICTIVE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

COMMIT;
