WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET PAGESIZE 200;
SET LINESIZE 200;
SET FEEDBACK ON;
SET SERVEROUTPUT ON;

PROMPT === RECREATE SCHEMA ===
@database/schema_oracle.sql

PROMPT === INSERT TEST DATA ===
INSERT INTO CLIENT (NAME, EMAIL, PHONE, ADDRESS, STATUS)
VALUES ('TEST_CLIENT', 'test.client@awss.local', '+21600000000', 'Test Address', 'ACTIVE');

INSERT INTO MACHINE (NOM, QUALITE)
VALUES ('TEST_MACHINE', 'A');

INSERT INTO CITERNE (CODE, CAPACITY_L, CURRENT_VOLUME_L, QUALITY_INDEX, TEMPERATURE_C, LAST_FILLING_AT, STATUS)
VALUES ('CIT-TEST-001', 5000, 1200, 1.10, 18.0, SYSDATE, 'ACTIVE');

INSERT INTO RECEPTION (LOT_NUMBER, RECEIVED_AT, QUANTITY_KG, QUALITY_GRADE, CLIENT_ID, STATUS)
VALUES (
    'LOT-TEST-001',
    SYSDATE,
    2000,
    'EXTRA',
    (SELECT ID FROM CLIENT WHERE NAME = 'TEST_CLIENT'),
    'RECEIVED'
);

INSERT INTO EXTRACTION (LOT_ID, MACHINE_ID, TARGET_CITERNE_ID, EXTRACTED_AT, INPUT_QUANTITY_KG, OUTPUT_OIL_L, YIELD_PERCENTAGE, QUALITY_RESULT, STATUS)
VALUES (
    (SELECT ID FROM RECEPTION WHERE LOT_NUMBER = 'LOT-TEST-001'),
    (SELECT ID FROM MACHINE WHERE NOM = 'TEST_MACHINE'),
    (SELECT ID FROM CITERNE WHERE CODE = 'CIT-TEST-001'),
    SYSDATE,
    2000,
    420,
    21.0,
    'OK',
    'DONE'
);

INSERT INTO MAINTENANCE_PREDICTIVE (MACHINE_ID, CITERNE_ID, PREDICTED_AT, PREDICTED_ISSUE, RISK_LEVEL, RECOMMENDED_ACTION, STATUS)
VALUES (
    (SELECT ID FROM MACHINE WHERE NOM = 'TEST_MACHINE'),
    (SELECT ID FROM CITERNE WHERE CODE = 'CIT-TEST-001'),
    SYSDATE,
    'Vibration anomaly',
    'MEDIUM',
    'Inspect bearings within 7 days',
    'OPEN'
);

COMMIT;

PROMPT === VERIFY COUNTS ===
SELECT 'CLIENT' AS TBL, COUNT(*) AS CNT FROM CLIENT
UNION ALL SELECT 'MACHINE', COUNT(*) FROM MACHINE
UNION ALL SELECT 'CITERNE', COUNT(*) FROM CITERNE
UNION ALL SELECT 'RECEPTION', COUNT(*) FROM RECEPTION
UNION ALL SELECT 'EXTRACTION', COUNT(*) FROM EXTRACTION
UNION ALL SELECT 'MAINTENANCE_PREDICTIVE', COUNT(*) FROM MAINTENANCE_PREDICTIVE;

PROMPT === VERIFY RELATION JOIN ===
SELECT e.ID,
       r.LOT_NUMBER,
       m.NOM AS MACHINE,
       c.CODE AS CITERNE,
       e.YIELD_PERCENTAGE
FROM EXTRACTION e
JOIN RECEPTION r ON r.ID = e.LOT_ID
JOIN MACHINE m ON m.ID = e.MACHINE_ID
JOIN CITERNE c ON c.ID = e.TARGET_CITERNE_ID
WHERE r.LOT_NUMBER = 'LOT-TEST-001';

EXIT;
