/* =========================================================
   VUES SQL POUR LES MODULES QT - VERSION FINALE
   ========================================================= */

CREATE OR REPLACE VIEW V_RECEPTION_CLIENT AS
SELECT
    r.ID,
    r.LOT_NUMBER,
    r.RECEIVED_AT,
    r.QUANTITY_KG,
    r.QUALITY_GRADE,
    r.STATUS AS RECEPTION_STATUS,
    c.ID AS CLIENT_ID,
    c.NAME AS CLIENT_NAME,
    c.EMAIL AS CLIENT_EMAIL,
    c.PHONE AS CLIENT_PHONE,
    c.STATUS AS CLIENT_STATUS
FROM RECEPTION r
JOIN CLIENT c ON c.ID = r.CLIENT_ID;

CREATE OR REPLACE VIEW V_EXTRACTION_DETAIL AS
SELECT
    e.ID AS EXTRACTION_ID,
    e.EXTRACTED_AT,
    e.INPUT_QUANTITY_KG,
    e.OUTPUT_OIL_L,
    e.YIELD_PERCENTAGE,
    e.QUALITY_RESULT,
    e.STATUS AS EXTRACTION_STATUS,

    r.ID AS RECEPTION_ID,
    r.LOT_NUMBER,
    r.RECEIVED_AT,
    r.QUANTITY_KG,
    r.QUALITY_GRADE,

    m.ID AS MACHINE_ID,
    m.NOM AS MACHINE_NAME,
    m.QUALITE AS MACHINE_QUALITE,

    c.ID AS CITERNE_ID,
    c.CODE AS CITERNE_CODE,
    c.CAPACITY_L,
    c.CURRENT_VOLUME_L,
    c.QUALITY_INDEX,
    c.TEMPERATURE_C
FROM EXTRACTION e
JOIN RECEPTION r ON r.ID = e.LOT_ID
JOIN MACHINE m   ON m.ID = e.MACHINE_ID
JOIN CITERNE c   ON c.ID = e.TARGET_CITERNE_ID;

CREATE OR REPLACE VIEW V_CITERNE_STOCK AS
SELECT
    c.ID,
    c.CODE,
    c.CAPACITY_L,
    c.CURRENT_VOLUME_L,
    c.QUALITY_INDEX,
    c.TEMPERATURE_C,
    c.STATUS,
    ROUND((c.CURRENT_VOLUME_L / NULLIF(c.CAPACITY_L, 0)) * 100, 2) AS FILLING_RATE
FROM CITERNE c;

CREATE OR REPLACE VIEW V_MAINTENANCE_PREDICTIVE_DETAIL AS
SELECT
    mp.ID,
    mp.PREDICTED_AT,
    mp.PREDICTED_ISSUE,
    mp.RISK_LEVEL,
    mp.RECOMMENDED_ACTION,
    mp.STATUS,
    m.ID AS MACHINE_ID,
    m.NOM AS MACHINE_NAME,
    c.ID AS CITERNE_ID,
    c.CODE AS CITERNE_CODE
FROM MAINTENANCE_PREDICTIVE mp
JOIN MACHINE m ON m.ID = mp.MACHINE_ID
LEFT JOIN CITERNE c ON c.ID = mp.CITERNE_ID;
